FROM node:20-alpine

ARG WORKSPACE
ENV WORKSPACE_NAME=${WORKSPACE}

WORKDIR /app

COPY package.json ./
COPY tsconfig.base.json ./
COPY packages ./packages
COPY services ./services

RUN npm install

# Build the shared database package first
RUN npm --workspace @artisan-haven/database run build

# Build the current service
RUN npm --workspace "$WORKSPACE_NAME" run build

CMD sh -c "npm --workspace \"$WORKSPACE_NAME\" run start"